### ISSUE TITLE
Refactor all data ingest scripts into a general class + subclassing

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/kowalski#145]
**Feature Summary**
There's quite a bit of duplicate code in those ingest scripts, so it would be useful to refactor them into a general `Ingestor` class + subclassing for the custom logic.

**Notes on implementation**

- `_id` type conversion:

```python
df["_id"] = df["_id"].astype(int)
```

- search and remove debug statements

**Comment by stefanv** [comment]
I would suggest starting with a set of utility functions and seeing how far it gets you.  Objects are really most useful for carrying state, and many of these scripts don't have a lot of common state that is shared.

**Comment by Theodlz** [comment]
The ingester tests' size has been reduced in the last PR, where we have an ingester class and import existing methods to avoid duplication. It could still be reduced further, but the current length of each test is very reasonable. Closing this issue for now.
