### ISSUE TITLE
A file is missing

### ISSUE THREAD

**Issue by marc-shen** [skyportal/kowalski#158]
When I'm using `./kowalski.py up` to build, there is an error `failed to compute cache key: "/version.txt" not found: not found`. 
In fact there is no version.txt file.

**Comment by mcoughlin** [comment]
@marc-shen This https://github.com/dmitryduev/kowalski/pull/157 is related. If you run with --build, does it work for you?

There are also known issues with getting kowalski built on an M1, assuming you are on the same system, but let's see.

**Comment by marc-shen** [comment]
I created a file by myself.
`version.txt`
`version = '0.0.0.1'`

**Comment by Theodlz** [comment]
Closing this issue as it seems to work just fine for both amd64 and arm64 now. Will reopen if needed.
