### ISSUE TITLE
The Docker + TensorFlow + M1 Mac Book is incompatible.

### ISSUE THREAD

**Issue by marc-shen** [skyportal/kowalski#159]
We can't create a file containing this program and the TensorFlow for Mac book M1 in docker.

**Comment by mcoughlin** [comment]
Yeah fundamentally this is the problem with needing to use Docker to use Kowalski. #93 is related.

**Comment by Theodlz** [comment]
Tensorflow now works just fine with Docker arm64, however librdkafka is the main blocker. Emulating amd64 on arm64 fixes kafka, but breaks Tensorflow. Ideally we do not want to use emulation anyway, so I will close this issue and open a new one for librdkafka.
