### ISSUE TITLE
iterrows in catalog ingestion casts all dtypes to float

### ISSUE THREAD

**Issue by bfhealy** [skyportal/kowalski#209]
When ingesting a parquet file using `ingest_catalog.py`, [this line](https://github.com/skyportal/kowalski/blob/2aa15c4587f5c7a022c9ab38bda3ae8e1c7077db/kowalski/ingesters/ingest_catalog.py#LL274C9-L274C9) casts all columns' dtypes to `float`. Thus the downstream checks for different dtypes will not work as intended.

Perhaps using `itertuples` instead would help by preserving the dtypes (at the expense of some re-working of the loop)? Note this could introduce a new issue where columns beginning with an underscore are renamed (e.g. `_id`, which gets mapped to `_1`). This might be avoided by setting `name=None` within `itertuples`.

**Comment by bfhealy** [comment]
For now I'm able to get around this issue by casting integers to the pandas `Int64` type using `column.astype("Int64")`, then saving in parquet format.

**Comment by Theodlz** [comment]
Hi @bfhealy. Do you maybe have a sample that I can use to try this out?

**Comment by Theodlz** [comment]
a PR addressing this issue has been merged
