### ISSUE TITLE
Milliquas crossmatch on alert package

### ISSUE THREAD

**Issue by tahumada** [skyportal/kowalski#214]
It'd be great if we could add milliquas to the crossmatches we do for alerts:
https://heasarc.gsfc.nasa.gov/W3Browse/all/milliquas.html

radius: 2 arcsec

fields to keep:

name
broad_type
rx_assoc_prob
qso_prob

**Comment by tahumada** [comment]
@Theodlz theeeeeoooooo

**Comment by tahumada** [comment]
I think these are the actual names in the catalog

Name
Type
RXpct
Qpct

**Comment by Theodlz** [comment]
Update: This has been added in production. We are monitoring new candidates to see if the crossmatch works as expected before closing this issue.

**Comment by Theodlz** [comment]
@tahumada did you get any of those on Fritz? There's no error I can see in Kowalski, so I would assume it works but I'd like to make sure so I can close this issue. Let me know if you get your annotations on any candidates
