### ISSUE TITLE
Non-docker-based build system

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/kowalski#93]
**Feature Summary**
In order to increase the dev speed, we need a non-docker-based build system.

**Implementation details**
Use a virtual environment for the python stuff. For devs, run the app with the `reload` parameter or use gunicorn with the `--reload` option. Keep mongo and the java/kafka stuff containerized.
Avoid `make` at all costs!

**Additional context**
The docker stuff should not be scrapped since it'll still be used in prod.

**Comment by kmshin1397** [comment]
Potential alternative or middle ground: mounting the files, or microservice to watch for file changes and copy into the image, etc.
